### ISSUE TITLE
TypeError: chalk is not a function

### ISSUE THREAD

**Issue by JakeGore** [webpack-contrib/config-loader#10] opened 2018-05-26 17:42 UTC
* Operating System: Ubuntu 18.04 LTS 64 bit
* Node Version: v8.10.0
* NPM Version: 3.5.2
* webpack Version: 4.9.1

### Expected Behavior

I am trying to bundle my javascript files with webpack.

### Actual Behavior

It's giving an error:
```
./@webpack-contrib/config-loader/lib/load.js:81
      log.error(chalk`An error ocurred while trying to find a config file
                     ^
```

### Code

```json
  "scripts": {
    "bundle": "webpack ./client/react/react.js -o ./public/js/react-bundle.js"
  }
```

**Comment by shellscape** [comment] 2018-05-26 18:32
Duplicate of #7,#8. Please search before opening a new isuue. Also please don't remove portions of the issue template.

**Closed by shellscape** 2018-05-26 18:32 UTC
Labels: x² ⋅ duplicate, x⁴ ⋅ invalid, 💩 template incomplete
